name: Preview site

on:
  push:
    branches-ignore:
      - master

jobs:
  preview:
    name: Build & deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build-site

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=site/dist --site=vanilla-extract
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
